apiVersion: v1
kind: Pod
metadata:
  name: helloworld
  labels:
    app: helloworld
spec:
  containers:
  - name: docker-demo
    image: sayems/docker-demo
    ports:
    - name: nodejs-port
      containerPort: 3000